// lista dei nomi di tutte le action su Redux
export const FETCH_PRODUCTS_LIST_REQUEST = "FETCH_PRODUCTS_LIST_REQUEST";
export const FETCH_PRODUCTS_LIST_SUCCESS = "FETCH_PRODUCTS_LIST_SUCCESS";
export const FETCH_PRODUCTS_LIST_FAILURE = "FETCH_PRODUCTS_LIST_FAILURE";

export const ADD_ITEM = "ADD_ITEM";